#!/usr/bin/env python
"""Self-contained reproduction script — generated by vivarium-dashboard.

Run from anywhere with the workspace's virtualenv, e.g.:
    .venv/bin/python autopoiesis-through-composition.py

Figures are written to:  reports/notebooks/figures
Set RERUN = False (below) to render the committed runs.db without re-simulating.
"""
import os as _os
import sys as _sys

# YAML / study text is UTF-8; force UTF-8 mode so file reads don't depend on the
# shell locale (a bare-CLI run under an ASCII locale otherwise crashes on non-ASCII).
if _os.environ.get("PYTHONUTF8") != "1":
    _os.environ["PYTHONUTF8"] = "1"
    _os.execv(_sys.executable, [_sys.executable, *_sys.argv])


# # Autopoiesis through composition
#
# _Investigation `autopoiesis-through-composition` — coder reproduction notebook._
#
# **Question.** Can a precarious, self-bounding identity — a cell that produces its own boundary —
# be assembled by composing existing parts, and how much of itself does each increment
# produce? Progress is measured, not asserted: by operational closure (the autopoiesis
# meter) and by precariousness (does the identity dissipate when self-production stops?).
#
# A whole-cell model built up as a self-producing network, increment by increment.
# The biological schema framework DRIVES acceptance: each study's verdict is the
# autopoiesis meter (operational closure: gap = requires \ provides \ boundary) plus
# the precariousness behavior test. The membrane — the self-produced boundary that
# the whole-cell-modeling lineage models as a given — is the part we build.
#
# ---
#
# This notebook re-runs each study with the workspace's own process-bigraph protocol and renders its figures. The text states the **question and parameters** only — the figures produced by each run are the results. Set `RERUN = False` in the setup cell to render the committed `runs.db` without re-simulating.

"""Self-contained reproduction of this investigation.

Generated by vivarium-dashboard (notebook_export). Each study below is re-run
live with the workspace's own process-bigraph protocol and its figures are
rendered from the resulting runs.db.
"""
import os
import sys
from pathlib import Path

# Resolve the repository root robustly so this notebook runs from a fresh clone
# at ANY path with no setup (no env var, no path editing). Priority:
#   1. $VIVARIUM_REPO, if it points at a real directory;
#   2. walk up from the notebook's working directory for the repo markers
#      (a directory holding both 'workspace/' and 'pyproject.toml') — Jupyter
#      starts in the notebook's dir, so a committed notebook finds its own root;
#   3. the absolute path it was generated for (back-compat for old layouts);
#   4. the current working directory (last resort).
def _find_repo_root(_start):
    for _cand in (_start, *_start.parents):
        if (_cand / "workspace").is_dir() and (_cand / "pyproject.toml").is_file():
            return _cand
    return None

REPO = None
_env = os.environ.get("VIVARIUM_REPO")
if _env and Path(_env).is_dir():
    REPO = Path(_env)
if REPO is None:
    REPO = _find_repo_root(Path.cwd().resolve())
if REPO is None and Path('/home/runner/work/viva-autopoiesis/viva-autopoiesis').is_dir():
    REPO = Path('/home/runner/work/viva-autopoiesis/viva-autopoiesis')
if REPO is None:
    REPO = Path.cwd()
sys.path.insert(0, str(REPO))
# Composite specs use repo-root-relative paths (datasets, caches), and the
# workspace's runner/renderer assume cwd == repo root — so run from there.
os.chdir(REPO)

# Re-simulate from scratch? Set False to render the committed runs.db (fast).
RERUN = True

# --- standard process-bigraph protocol: register the workspace's Core ---
from pbg_autopoiesis.core import build_core
core = build_core()

# --- imported from the repo this notebook was generated for ---


import contextlib as _contextlib, io as _io
@_contextlib.contextmanager
def quiet():
    """Silence the simulator's verbose per-step stdout so the notebook
    output stays readable (the figures below are the results)."""
    with _contextlib.redirect_stdout(_io.StringIO()):
        yield

import html as _htmlmod
def show_viz(_h, height=560):
    """Display a visualization's HTML in an isolated iframe.

    The figures embed their own scripts (e.g. Plotly); JupyterLab does not
    execute <script> tags from display(HTML(...)), so an iframe srcdoc is
    used instead — the browser runs the scripts inside the frame."""
    display(HTML(
        '<iframe srcdoc="{}" style="width:100%;height:{}px;border:0">'
        '</iframe>'.format(_htmlmod.escape(_h, quote=True), height)
    ))

import json as _json
def describe_spec(spec):
    """Print a composite spec's structure (parameters, processes, wiring)
    then the full editable dict. The spec is plain data — assign to any
    field (e.g. spec['state'][proc]['config'][...]) before building."""
    print("composite:", spec.get("name"))
    if spec.get("description"):
        print("description:", str(spec["description"]).strip())
    _params = spec.get("parameters") or {}
    if _params:
        print("\nparameters (filled into ${name} placeholders):")
        for _p, _pdef in _params.items():
            print(f"  {_p}: default={_pdef.get('default')!r}  type={_pdef.get('type')}")
    print("\nprocesses (node -> address):")
    for _node, _body in (spec.get("state") or {}).items():
        if not (isinstance(_body, dict) and _body.get("_type") == "process"):
            continue
        print(f"  {_node}  ->  {_body.get('address')}   interval={_body.get('interval')!r}")
        for _port in ("inputs", "outputs"):
            if _body.get(_port):
                print(f"      {_port} ports: {_body[_port]}")
    print("\nfull editable spec dict:")
    print(_json.dumps(spec, indent=2, default=str))

# ## Study: `study-1-membrane-metabolism-loop`
#
# **Objective.** Assemble the smallest precarious, self-bounding identity by composing a toy metabolism,
# a membrane that grows from its own lipids (and decays without them), and a boundary whose
# volume is DERIVED from the membrane — then verify, with the autopoiesis meter, that the
# network is operationally closed (modulo nutrient) and that the identity is precarious:
# fed it persists, starved it dissipates.

# ### Parameters

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: study-1-membrane-metabolism-loop ===
STUDY = 'study-1-membrane-metabolism-loop'
STUDY_DIR = REPO / 'studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ### Visualizations
#
# _Results are shown by the figures below, produced by the run above._

# **precariousness**

def _save_viz(study, slug, html):
    d = REPO / 'reports/notebooks/figures' / study
    d.mkdir(parents=True, exist_ok=True)
    out = d / (slug + '.html')
    out.write_text(html, encoding='utf-8')
    print('  wrote', out)


# precariousness
_save_viz('study-1-membrane-metabolism-loop', 'precariousness', _render_one('', {}, RUNS_DB, STUDY_YAML))

# **dynamics**

# dynamics
_save_viz('study-1-membrane-metabolism-loop', 'dynamics', _render_one('', {}, RUNS_DB, STUDY_YAML))

# **emergent_boundary**

# emergent_boundary
_save_viz('study-1-membrane-metabolism-loop', 'emergent_boundary', _render_one('', {}, RUNS_DB, STUDY_YAML))

# **volume_coupling**

# volume_coupling
_save_viz('study-1-membrane-metabolism-loop', 'volume_coupling', _render_one('', {}, RUNS_DB, STUDY_YAML))

# **closure_cycle**

# closure_cycle
_save_viz('study-1-membrane-metabolism-loop', 'closure_cycle', _render_one('', {}, RUNS_DB, STUDY_YAML))

# **phase_portrait**

# phase_portrait
_save_viz('study-1-membrane-metabolism-loop', 'phase_portrait', _render_one('', {}, RUNS_DB, STUDY_YAML))

# ### Acceptance criteria
#
# _Pre-registered checks (criteria/thresholds only — run the cells above to evaluate them)._
#
# | test | measures | passes if |
# | --- | --- | --- |
# | operational-closure | kind=derived_scalar field=closure_gap_size | op <= value 0 provenance {'kind': 'theory', 'note': 'gap = ∅ is the definitional autopoietic criterion (operational closure of constraints; Maturana-Varela, Montévil-Mossio): a network is closed iff every requirement is self-provided. The threshold is the theory, not a tuned value.'} |
# | precariousness | kind=derived_scalar field=precariousness_ratio | op < value 0.3 provenance {'kind': 'calibration', 'note': '0.3 starved/fed ratio is a calibration band set so the self-producing loop (≈0.035) passes with wide margin while an externally-maintained mimic (≈9x persistent) fails — calibrated against the two controls, not a literature value.'} |
# | identity-persists-when-fed | kind=derived_scalar field=fed_volume_growth | op >= value 1.0 |

# ## Study: `study-2-spatial-containment`
#
# **Objective.** Study 1 had no space — "inside" was a scalar volume. In a medium the self-produced
# interior would diffuse away and the individual would dissolve. Put the cell on a 1-D
# lattice where interior content DIFFUSES and the self-produced membrane GATES the
# boundary flux, and show that the membrane — built by the metabolism it contains —
# is what holds the individual together against dispersion. The autopoiesis of
# containment, with precariousness extended to space.

# ### Parameters

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: study-2-spatial-containment ===
STUDY = 'study-2-spatial-containment'
STUDY_DIR = REPO / 'studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ### Visualizations
#
# _Results are shown by the figures below, produced by the run above._

# **containment_profiles**

# containment_profiles
_save_viz('study-2-spatial-containment', 'containment_profiles', _render_one('', {}, RUNS_DB, STUDY_YAML))

# **kymograph**

# kymograph
_save_viz('study-2-spatial-containment', 'kymograph', _render_one('', {}, RUNS_DB, STUDY_YAML))

# **containment_over_time**

# containment_over_time
_save_viz('study-2-spatial-containment', 'containment_over_time', _render_one('', {}, RUNS_DB, STUDY_YAML))

# ### Acceptance criteria
#
# _Pre-registered checks (criteria/thresholds only — run the cells above to evaluate them)._
#
# | test | measures | passes if |
# | --- | --- | --- |
# | containment | kind=derived_scalar field=containment_ratio | op >= value 3.0 provenance {'kind': 'calibration', 'note': '3x interior/exterior concentration is a clear-separation band: the self-produced membrane case (~60x) passes with margin, calibrated so containment is unambiguous rather than marginal. Not a literature value.'} |
# | membrane-counters-diffusion | kind=derived_scalar field=membrane_effect | op >= value 2.0 provenance {'kind': 'theory', 'note': 'The membrane must more than double containment vs metabolism-alone for the self-produced boundary (not diffusion physics) to be the cause; 2x is the minimal "membrane dominates" criterion implied by the discriminative claim.'} |
# | spatial-precariousness | kind=derived_scalar field=precariousness_collapse | op < value 0.3 |

# ## Study: `study-3-adaptive-chemotaxis`
#
# **Objective.** Place the precarious individual in an environment with a nutrient gradient and give
# it a sensorimotor loop: sense the local nutrient, run-and-tumble (tumble less when
# nutrient is rising), move. The nutrient feeds the metabolism that maintains the
# membrane that keeps it alive. Show that a chemotactic agent climbs the gradient,
# finds food, and survives — while a blind agent random-walks, starves, and dissolves.
# This is where life becomes mind: the gradient is MEANINGFUL from the perspective of
# the precarious identity (up-gradient = viable, down-gradient = dissolution). Value is
# grounded in the cell's own viability, not assigned from outside — sense-making, and
# agency in service of self-maintenance.

# ### Parameters

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: study-3-adaptive-chemotaxis ===
STUDY = 'study-3-adaptive-chemotaxis'
STUDY_DIR = REPO / 'studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ### Visualizations
#
# _Results are shown by the figures below, produced by the run above._

# **trajectories**

# trajectories
_save_viz('study-3-adaptive-chemotaxis', 'trajectories', _render_one('', {}, RUNS_DB, STUDY_YAML))

# **survival**

# survival
_save_viz('study-3-adaptive-chemotaxis', 'survival', _render_one('', {}, RUNS_DB, STUDY_YAML))

# **landscape**

# landscape
_save_viz('study-3-adaptive-chemotaxis', 'landscape', _render_one('', {}, RUNS_DB, STUDY_YAML))

# ### Acceptance criteria
#
# _Pre-registered checks (criteria/thresholds only — run the cells above to evaluate them)._
#
# | test | measures | passes if |
# | --- | --- | --- |
# | chemotaxis-survival | kind=derived_scalar field=chemotaxis_survival | op >= value 0.6 |
# | agency-advantage | kind=derived_scalar field=survival_advantage | op >= value 1.5 provenance {'kind': 'calibration', 'note': '1.5x advantage band set so sensing must clearly beat the blind random-walk control (~0.35 survival); calibrated against the negative control rather than a literature effect size (observed 2.33x ± 0.26 over 12 seeds).'} |
# | sense-making | kind=derived_scalar field=gradient_advantage | op >= value 1.15 provenance {'kind': 'theory', 'note': '>1 means the agent experiences more food than chance; 1.15 is a minimal "the gradient is made to matter" margin above parity — a theory-motivated floor for sense-making, not a calibrated or literature value.'} |

# ## Study: `study-4-growth-division`
#
# **Objective.** The precarious individual grows as its autopoietic loop runs and, past a size
# threshold, DIVIDES into two daughters. The membrane is partitioned with noise so
# daughters differ in size; a heritable trait is inherited with mutation so lineages
# DIVERSIFY over generations — one individual becomes a population of non-identical
# individuals. Division is itself precarious: a daughter that inherits too little
# membrane to maintain itself dissolves — reproduction has a viability cost. This
# heterogeneous population is the substrate on which study 5's selection can act.

# ### Parameters

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: study-4-growth-division ===
STUDY = 'study-4-growth-division'
STUDY_DIR = REPO / 'studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ### Visualizations
#
# _Results are shown by the figures below, produced by the run above._

# **population**

# population
_save_viz('study-4-growth-division', 'population', _render_one('', {}, RUNS_DB, STUDY_YAML))

# **diversification**

# diversification
_save_viz('study-4-growth-division', 'diversification', _render_one('', {}, RUNS_DB, STUDY_YAML))

# **heterogeneity**

# heterogeneity
_save_viz('study-4-growth-division', 'heterogeneity', _render_one('', {}, RUNS_DB, STUDY_YAML))

# ### Acceptance criteria
#
# _Pre-registered checks (criteria/thresholds only — run the cells above to evaluate them)._
#
# | test | measures | passes if |
# | --- | --- | --- |
# | reproduction | kind=derived_scalar field=final_population | op >= value 10 |
# | heterogeneity | kind=derived_scalar field=composition_heterogeneity | op >= value 0.05 provenance {'kind': 'exploratory', 'note': 'Existence-level band (this is an exploratory study): the threshold asks only whether trait diversity emerges at all (spread > ~0), not a calibrated or literature-anchored magnitude.'} |
# | division-precariousness | kind=derived_scalar field=division_mortality | op >= value 0.01 provenance {'kind': 'exploratory', 'note': 'Existence-level band: any non-zero daughter mortality demonstrates reproduction carries a viability cost. Exploratory threshold (does the cost occur at all?), not a calibrated rate.'} |

# ## Study: `study-5-adversarial-probes`
#
# **Objective.** Turn the demonstration into a test: challenge the autopoiesis framework with
# systems that should NOT qualify, and check that the metric REJECTS them. Two
# probes — an externally-maintained mimic (persistence supplied from outside, not
# self-produced) and a network missing a self-production step (no membrane
# producer). The study passes only if the metric rejects both, showing the
# criteria discriminate genuine self-production from superficial similarity.

# ### Parameters

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: study-5-adversarial-probes ===
STUDY = 'study-5-adversarial-probes'
STUDY_DIR = REPO / 'studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ### Acceptance criteria
#
# _Pre-registered checks (criteria/thresholds only — run the cells above to evaluate them)._
#
# | test | measures | passes if |
# | --- | --- | --- |
# | rejects-external-maintenance | kind=derived_scalar field=external_maintenance_persistence | op >= value 3.0 provenance {'kind': 'calibration', 'note': 'The mimic must be ≥3x more persistent than the self-producing loop when starved to count as "rejected" (not precarious); calibrated against the self-producing-loop positive control, mirroring study-1\'s precariousness band.'} |
# | rejects-broken-closure | kind=derived_scalar field=broken_network_gap | op > value 0 provenance {'kind': 'theory', 'note': 'Any non-empty closure gap means a required type is not self-produced, so the network is definitionally not operationally closed — the threshold is the autopoietic closure definition, not a tuned value.'} |
